/*
 * File: app/view/emiActivityLabel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.emiActivityLabel', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'label',
				html: '<center><b>What are you doing?</b></center>'
			},
			{
				xtype: 'label',
				html: 'Seems like you are doing something interesting.'
			},
			{
				xtype: 'checkboxfield',
				label: 'Driving',
				labelWidth: '80%',
				value: 'Feet'
			},
			{
				xtype: 'checkboxfield',
				label: 'Eating',
				labelWidth: '80%',
				value: ''
			},
			{
				xtype: 'checkboxfield',
				label: 'Walking',
				labelWidth: '80%'
			},
			{
				xtype: 'checkboxfield',
				label: 'Socializing',
				labelWidth: '80%'
			},
			{
				xtype: 'checkboxfield',
				label: 'Preparing food',
				labelWidth: '80%'
			},
			{
				xtype: 'checkboxfield',
				label: 'TV/Computer',
				labelWidth: '80%'
			},
			{
				xtype: 'checkboxfield',
				label: 'Reading',
				labelWidth: '80%'
			},
			{
				xtype: 'button',
				action: 'exercise',
				text: 'Done!'
			}
		]
	}

});