/*
 * File: app/view/emiiPerspective.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.emiiPerspective', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'label',
				html: '<center><b>Perspective-taking</b></center>'
			},
			{
				xtype: 'label',
				html: 'Take the perspective of your child to see how they are feeling.'
			},
			{
				xtype: 'selectfield',
				label: 'How are you feeling right now?',
				labelWidth: '50%',
				labelWrap: true,
				maxLength: 20,
				placeHolder: 'Select...'
			},
			{
				xtype: 'selectfield',
				label: 'How might your child be feeling right now?',
				labelWidth: '50%',
				labelWrap: true,
				maxLength: 20,
				placeHolder: 'Select...'
			},
			{
				xtype: 'button',
				text: 'Done!'
			}
		]
	}

});