/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
	enabled: true
});

Ext.application({
	models: [
		'EMI',
		'User',
		'Feed'
	],
	stores: [
		'EMIs',
		'Feeds'
	],
	views: [
		'emiTensionCheck',
		'emiMountain',
		'emiiPerspective',
		'emiFGM',
		'emiFGMFollowUp',
		'emiFGMList',
		'emiActivityLabel',
		'emiWeeklyIntentionP1',
		'emiWeeklyIntentionP2',
		'emiDailyGoal',
		'emaStress',
		'emaPleasantness',
		'emaEmotion',
		'MainTabs'
	],
	name: 'HEART',
	controllers: [
		'EMIController',
		'ExerciseController'
	],

	launch: function() {

		Ext.create('HEART.view.MainTabs', {fullscreen: true});
	}

});
