/*
 * File: app/controller/EMIController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.controller.EMIController', {
	extend: 'Ext.app.Controller',

	config: {
		refs: {
			mainView: 'mainview',
			exercises: '#exercises'
		},

		control: {
			"#exerciseList": {
				itemtap: 'onListItemTap'
			},
			"#exercises": {
				hide: 'onNavigationviewHide'
			}
		}
	},

	onListItemTap: function(dataview, index, target, record, e, options) {

		var pnl = Ext.create('HEART.view.' + record.get("type"));
		pnl.record_data = record;
		this.getExercises().push(pnl);


	},

	onNavigationviewHide: function(component, options) {
		this.getExercises().pop();
	},

	launch: function() {
		//console.log(this.getMainContainer());

		this.getExercises().getNavigationBar().hide();

		//this.getExercises().setActiveItem(pnl);
	}

});