/*
 * File: app/controller/ExerciseController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.controller.ExerciseController', {
	extend: 'Ext.app.Controller',

	config: {
		refs: {
			exercises: '#exercises',
			emaStress: '#emaStress'
		},

		control: {
			"button[action=exercise]": {
				tap: 'onButtonTap'
			}
		}
	},
	
	onButtonTap: function(button, e, options) {
		var form = button.parent;
		console.log(form);
		var values = form.getValues();
		console.log(values);

		var feed = form.record_data.get("feed_title");

		Ext.getStore("Feeds").add({title: feed, timestamp: Date.now()});
		Ext.getStore("Feeds").sort("timestamp", 'DESC');
		Ext.getStore("Feeds").sync();
		
		
		form.submit({
			url: 'login.php',
			method: 'POST',
			success: function(form, result) {
				Ext.Msg.alert('', 'Data submitted successfully!');
			},
			failure: function(form, result) {
				Ext.Msg.alert('', 'Still under development.  Data currently not collected');
			}
		});

		this.getExercises().pop();
	}

});