/*
 * File: app/controller/MainController.js
 * Date: Wed Apr 10 2013 17:10:20 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.controller.MainController', {
	extend: 'Ext.app.Controller',

	config: {
		refs: {
			homePanel: '#homepanel',
			stressed: '#stressed'
		},

		control: {
			"#homepanel #editIntention": {
				tap: 'onEditIntentionTap'
			},
			"#homepanel #homeSlider": {
				change: 'onHomeSliderChange'
			},
			"#homepanel #homeDone": {
				tap: 'onHomeDoneTap'
			},
			"#settings #setNotifications": {
				tap: 'onPushSettingEdit'
			},
			"formpanel": {
				activeitemchange: 'onHomePanelActive'
			},
			"button[text=Done]": {
				tap: 'onButtonDoneTap'
			}
		}
	},

	onEditIntentionTap: function(button, e, eOpts) {
		var intention = Ext.create('HEART.view.EMIIntentionSet');
		Ext.Viewport.setActiveItem(intention);
	},

	onHomeSliderChange: function(me, Slider, thumb, newValue, oldValue, eOpts) {
		var value = Slider.getValue();
		me.parent.child('#homeDone').enable();
		setTimeout(function(){Slider.setValue(value/2)}, 60000);
	},

	onHomeDoneTap: function(button, e, eOpts) {
		var slider = button.parent.child('sliderfield');
		var stress = slider.getValue();

		var content = { type: 'homePanel', user: 'kyle', data: stress };

		var succ = function(response) {
			console.log(response);
		};

		var fail = function(response) {
			var feeds = Ext.getStore("Feeds");
			feeds.add({timestamp: Date.now(), type: 'homePanel', data: stress, mark: false});
			feeds.sort("timestamp", 'DESC');		
			feeds.sync();
		};

		AJAX.toSensor(content, succ, fail);
	},

	onPushSettingEdit: function(button, e, eOpts) {
		var users = Ext.getStore('Users');
		var uuid = Ext.device.Device.uuid;
		uuid = 'qwertyuiop';
		values = button.parent.getValues();
		values.uuid = uuid;

		var index = users.findBy(function(record){ return record.data.uuid==uuid });

		if(index >= 0){
			users.removeAll();	
		}

		users.add(values);
		users.sync();

		this.getHomePanel().parent.getTabBar().show();

		var form = Ext.create('HEART.view.EMIPushSlider');
		Ext.Viewport.setActiveItem(form);
	},

	onHomePanelActive: function(container, value, oldValue, eOpts) {
		this.renderIntention();
	},

	onButtonDoneTap: function(button, e, eOpts) {
		button.disable();
		setTimeout(function(){button.enable()}, 300000);
	},

	renderIntention: function() {
		var feeds = Ext.getStore('Feeds');
		intention = feeds.findRecord('type', 'intention');
		if(intention!=null){
			var text = intention.get('data');
			this.getHomePanel().child('button').setText(text);
		}
	},

	launch: function() {
		this.renderIntention();

		setInterval(function(){if(Ext.device.Connection.isOnline()){AJAX.sync()}}, 4096);
	}

});