/*
 * File: app/store/EMIs.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.store.EMIs', {
	extend: 'Ext.data.Store',

	requires: [
		'HEART.model.EMI'
	],

	config: {
		autoLoad: true,
		data: [
			{
				title: 'Stress',
				type: 'emaStress',
				category: 'Check-ins',
				feed_title: 'Stress Checkin'
			},
			{
				title: '3-areas',
				type: 'emaPleasantness',
				category: 'Check-ins',
				feed_title: 'Pleasantness Checkin'
			},
			{
				title: 'Emotions',
				type: 'emaEmotion',
				category: 'Check-ins',
				feed_title: 'Emotion Checkin'
			},
			{
				title: 'Test Mountain',
				type: 'emiMountain',
				category: 'Guided audio',
				feed_title: 'Mountain Exercise'
			},
			{
				title: 'Release tension',
				type: 'emiTensionCheck',
				category: 'Practices',
				feed_title: 'Tension Check'
			},
			{
				title: 'Perspective',
				type: 'emiPerspective',
				category: 'Practices',
				feed_title: 'Perspective Ex.'
			},
			{
				title: 'Acitivity insight',
				type: 'emiActivityLabel',
				category: 'Practices',
				feed_title: 'Activity Label'
			},
			{
				title: 'Take a photo',
				type: 'emiFGM',
				category: 'Feel Good Moment',
				feed_title: 'Take a photo'
			},
			{
				title: 'Photo List',
				type: 'emiFGMList',
				category: 'Feel Good Moment',
				feed_title: 'Photo List'	
			}
		],
		groupField: 'category',
		model: 'HEART.model.EMI',
		storeId: 'EMIs'
	}
});