/*
 * File: app/store/EMXs.js
 * Date: Thu Apr 11 2013 16:46:59 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.store.EMXs', {
	extend: 'Ext.data.Store',

	requires: [
		'HEART.model.EMX'
	],

	config: {
		autoLoad: true,
		data: [
			{
				title: 'What\'s most important?',
				type: 'emiReflection1',
				category: 'Reflections'
			},
			{
				title: 'What did I really want from this?',
				type: 'emiReflection2',
				category: 'Reflections'
			},
			{
				title: 'What\'s preventing me?',
				type: 'emiReflection3',
				category: 'Reflections'
			},
			{
				title: 'What\'s more important than now?',
				type: 'emiReflection4',
				category: 'Reflections'
			},
			{
				title: 'What habits are present?',
				type: 'emiReflection5',
				category: 'Reflections'
			},
			{
				title: 'Compassion Meditation',
				type: 'emiAudio1',
				category: 'AUDIOS'
			},
			{
				title: 'Perspective Taking',
				type: 'emiAudio3',
				category: 'AUDIOS'
			},
			{
				title: 'Guided Elaxation',
				type: 'emiAudio2',
				category: 'AUDIOS'
			},
			{
				title: 'Stress & Calm',
				type: 'emaType1',
				category: 'CHECK-INS'
			},
			{
				title: 'Emotion awareness',
				type: 'emaType2',
				category: 'CHECK-INS'
			},
			{
				title: 'Emotion intensity',
				type: 'emaType3',
				category: 'CHECK-INS'
			}
		],
		groupField: 'category',
		model: 'HEART.model.EMX',
		storeId: 'EMXs'
	}
});