/*
 * File: app/model/EMX.js
 * Date: Mon Apr 01 2013 15:53:28 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.model.EMX', {
	extend: 'Ext.data.Model',

	config: {
		fields: [
			{
				allowNull: false,
				name: 'title',
				type: 'string'
			},
			{
				name: 'type',
				type: 'string'
			},
			{
				name: 'feed_title',
				type: 'string'
			},
			{
				name: 'category'
			}
		]
	}
});