/*
 * File: app/model/User.js
 * Date: Wed Apr 03 2013 18:25:33 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.model.User', {
	extend: 'Ext.data.Model',

	config: {
		fields: [
			{
				name: 'name'
			},
			{
				name: 'child_name'
			},
			{
				name: 'gender'
			},
			{
				name: 'height'
			},
			{
				name: 'weight'
			},
			{
				name: 'wake_time'
			},
			{
				name: 'sleep_time'
			},
			{
				name: 'push_set'
			},
			{
				allowNull: false,
				name: 'uuid'
			}
		]
	}
});