/*
 * File: app/controller/EMIController.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.controller.EMIController', {
	extend: 'Ext.app.Controller',

	config: {
		refs: {
			mainTabPanel: '#mainTabPanel',
			mainContainer: '#mainContainer'
		},

		control: {
			"#emiList": {
				itemtap: 'onListItemTap'
			}
		}
	},

	onListItemTap: function(dataview, index, target, record, e, options) {
		console.log(record);
		var pnl = Ext.create('HEART.view.emi' + record.get("type"));
		this.getMainContainer().push(pnl);

		console.log("tap2");
	},

	launch: function() {
		console.log(this.getMainContainer());
		var pnl = Ext.create('HEART.view.MainTabs');
		this.getMainContainer().getNavigationBar().hide();
		this.getMainContainer().setActiveItem(pnl);
	}

});