/*
 * File: app/view/DAILYLOG.js
 * Date: Tue Jul 02 2013 20:03:21 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.DAILYLOG', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'fieldset',
				itemId: 'fset',
				items: [
					{
						xtype: 'label',
						html: 'My Daily Log',
						itemId: 'title',
						listeners: [
							{
								fn: function(component, eOpts) {
									component.element.on({
										tap : function(e, t){

											content = '<p>Instructions: "Each night we ask a few quick questions about your day’s activities. These should take less than 1 minute to complete. We don’t expect you to complete it every night, but the more the better, for the research and for your own tracking. A missing value on meditation, mindful eating, or exericise will count as a 0 (not done that day). Thank you so much for committing to the mindful path for your life and for this research.”</p>';

											Ext.create('Ext.Panel', {
												hideOnMaskTap: true,
												autoDestroy: true, 
												modal: true,
												html: content,
												padding: 10,
												left: 0,
												style: "color: rgb(128,128,128); font-size: 12px"
											}).showBy(component);

										}
									});
								},
								event: 'initialize'
							}
						]
					},
					{
						xtype: 'sliderfield',
						itemId: 'thoughts',
						label: 'How much were you lost in thoughts (of past or future) in the past 5 minutes? <br/><br> <div><span style="float:right">Very Much</span><span>Not at all</span></div>',
						labelAlign: 'top',
						labelWrap: true,
						name: 'thoughts',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						itemId: 'notice',
						label: 'Did you notice being present and aware (in the activity you were engaged in) in the past 10 minutes? <br/><br/> <div><span style="float:right">Very Much</span><span>Not at all</span></div>',
						labelAlign: 'top',
						labelWrap: true,
						name: 'notice',
						value: [
							50
						]
					},
					{
						xtype: 'checkboxfield',
						html: '(body scan, recorded or self-guided meditation, or mindful breathing)',
						itemId: 'meditation',
						styleHtmlContent: true,
						label: 'Any formal meditation today?',
						labelAlign: 'top',
						labelWidth: '',
						labelWrap: true
					},
					{
						xtype: 'selectfield',
						itemId: 'howlong',
						label: 'How long ?',
						labelWidth: '50%',
						options: [
							{
								text: '5 min or less',
								value: '0'
							},
							{
								text: 'Up to 30 min',
								value: '1'
							},
							{
								text: 'More than 30 min',
								value: '2'
							}
						]
					},
					{
						xtype: 'checkboxfield',
						itemId: 'mindful',
						label: 'Any mindful eating today?',
						labelWidth: '',
						labelWrap: true
					},
					{
						xtype: 'selectfield',
						itemId: 'exercise',
						label: 'Any exercise today? (10min or more)',
						labelAlign: 'top',
						labelWidth: '100%',
						labelWrap: true,
						options: [
							{
								text: 'None',
								value: '0'
							},
							{
								text: 'Walking (or equivalent)',
								value: '1'
							},
							{
								text: 'More than 30 minAerobic (like jogging)',
								value: '2'
							},
							{
								text: 'Mind-body activity (yoga, chi gung, etc)',
								value: '3'
							}
						]
					},
					{
						xtype: 'container',
						hidden: true,
						hideAnimation: {
							type: 'fadeOut',
							duration: 2048
						},
						itemId: 'group',
						showAnimation: {
							type: 'fadeIn',
							duration: 2048
						},
						items: [
							{
								xtype: 'label',
								html: '<b>THANK YOU</b>',
								itemId: 'thanks',
								styleHtmlContent: true
							},
							{
								xtype: 'label',
								html: 'Have a few moments to reflect on your day?',
								itemId: 'describe'
							},
							{
								xtype: 'button',
								itemId: 'ok',
								text: 'YES'
							},
							{
								xtype: 'button',
								itemId: 'no',
								text: 'NO'
							}
						]
					}
				]
			}
		],
		listeners: [
			{
				fn: 'onAnyExerciseChange',
				event: 'change',
				delegate: '#exercise'
			},
			{
				fn: 'onOKTap',
				event: 'tap',
				delegate: '#ok'
			},
			{
				fn: 'onNoTap',
				event: 'tap',
				delegate: '#no'
			}
		]
	},

	onAnyExerciseChange: function(selectfield, newValue, oldValue, eOpts) {
		selectfield.parent.child('#group').show();
	},

	onOKTap: function(button, e, eOpts) {
		this.parent.pop();

		form = Ext.create('HEART.view.Experience');
		this.parent.push(form);
	},

	onNoTap: function(button, e, eOpts) {
		this.parent.pop();
	}

});