/*
 * File: app/view/EMAType2.js
 * Date: Sun Apr 28 2013 11:55:28 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMAType2', {
	extend: 'Ext.form.Panel',

	config: {
		scrollable: 'vertical',
		items: [
			{
				xtype: 'label',
				cls: 'desc',
				html: 'What is happening in your body right now?',
				margin: '8px'
			},
			{
				xtype: 'fieldset',
				goola: 'ema',
				items: [
					{
						xtype: 'sliderfield',
						label: 'The amount of pleasant feeling I am experiencing is: <br/> (left=none, right=a lot)',
						labelAlign: 'top',
						labelWrap: true,
						name: 'pleasantness',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'The amount of unpleasant feeling I am experiencing is:',
						labelAlign: 'top',
						labelWrap: true,
						name: 'unpleasantness',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'My energy level in this moment is:',
						labelAlign: 'top',
						labelWrap: true,
						name: 'energy',
						value: [
							50
						]
					},
					{
						xtype: 'button',
						action: 'exercise',
						text: 'Done'
					}
				]
			}
		]
	}

});