/*
 * File: app/view/EMAType5.js
 * Date: Wed Apr 17 2013 21:44:41 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMAType5', {
	extend: 'Ext.form.Panel',

	config: {
		scrollable: 'vertical',
		items: [
			{
				xtype: 'fieldset',
				instructions: 'goola',
				title: 'What is the state of your mind in this moment?',
				items: [
					{
						xtype: 'sliderfield',
						label: 'Calm',
						labelAlign: 'top',
						labelWrap: true,
						name: 'calm',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Agitated',
						labelAlign: 'top',
						labelWrap: true,
						name: 'agitated',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Restless',
						labelAlign: 'top',
						labelWrap: true,
						name: 'restless',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Open',
						labelAlign: 'top',
						labelWrap: true,
						name: 'open',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Constricted',
						labelAlign: 'top',
						labelWrap: true,
						name: 'constricted',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Balanced',
						labelAlign: 'top',
						labelWrap: true,
						name: 'balanced',
						value: [
							50
						]
					},
					{
						xtype: 'button',
						action: 'exercise',
						text: 'Done'
					}
				]
			}
		]
	}

});