/*
 * File: app/view/EMAType3.js
 * Date: Fri Jun 28 2013 14:53:53 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMAType3', {
	extend: 'Ext.form.Panel',

	config: {
		scrollable: 'vertical',
		items: [
			{
				xtype: 'label',
				cls: 'desc',
				html: 'What emotions are you experiencing in this moment? <br/> <br/> <div><span style="float:right">a lot</span><span>none</span></span>',
				margin: '8px'
			},
			{
				xtype: 'fieldset',
				goola: 'ema',
				items: [
					{
						xtype: 'sliderfield',
						label: 'I am feeling anger:',
						labelAlign: 'top',
						labelWrap: true,
						name: 'anger',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'I am feeling sad:',
						labelAlign: 'top',
						labelWrap: true,
						name: 'sadness',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'I am feeling joyful',
						labelAlign: 'top',
						labelWrap: true,
						name: 'joy',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'I am feeling calm:',
						labelAlign: 'top',
						labelWrap: true,
						name: 'calm',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'I am feeling fearful or anxious:',
						labelAlign: 'top',
						labelWrap: true,
						name: 'fora',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'I am feeling grateful:',
						labelAlign: 'top',
						labelWrap: true,
						name: 'grate',
						value: [
							50
						]
					},
					{
						xtype: 'button',
						action: 'exercise',
						text: 'Done'
					}
				]
			}
		]
	}

});