/*
 * File: app/view/EMAType4.js
 * Date: Wed Apr 17 2013 21:47:41 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMAType4', {
	extend: 'Ext.form.Panel',

	config: {
		scrollable: 'vertical',
		items: [
			{
				xtype: 'label',
				html: 'First, take a moment. Then, are you aware of trying to not feel something right now?<br/>(left=none, right=a lot)'
			},
			{
				xtype: 'fieldset',
				instructions: 'goola',
				items: [
					{
						xtype: 'sliderfield',
						label: 'Anger',
						labelAlign: 'top',
						labelWrap: true,
						name: 'anger',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Sadness',
						labelAlign: 'top',
						labelWrap: true,
						name: 'sadness',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Shame',
						labelAlign: 'top',
						labelWrap: true,
						name: 'shame',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Anxiety',
						labelAlign: 'top',
						labelWrap: true,
						name: 'anxiety',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Happiness',
						labelAlign: 'top',
						labelWrap: true,
						name: 'happiness',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'Other',
						labelAlign: 'top',
						labelWrap: true,
						name: 'other',
						value: [
							50
						]
					},
					{
						xtype: 'sliderfield',
						label: 'How much energy are you using to avoid these feelings (if any)?',
						labelAlign: 'top',
						labelWrap: true,
						name: 'energy',
						value: [
							50
						]
					},
					{
						xtype: 'button',
						action: 'exercise',
						text: 'Done'
					}
				]
			}
		]
	}

});