/*
 * File: app/view/emiFGM.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.emiFGM', {
	extend: 'Ext.form.Panel',

	config: {
		showAnimation: 'slideIn',
		modal: false,
		items: [
			{
				xtype: 'label',
				html: '<center><b>Feel-Good Moment (FGM)</b></center>'
			},
			{
				xtype: 'label',
				html: 'Take a photo of something beautiful happening around you right now.'
			},
			{
				xtype: 'button',
				text: 'Press here to take photo...'
			},
			{
				xtype: 'button',
				text: 'Done!'
			}
		]
	}

});