/*
 * File: app/view/emiFGMFollowUp.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.emiFGMFollowUp', {
	extend: 'Ext.form.Panel',
	xtype: 'fgmfollowup',
	
	config: {
		items: [
			{
				xtype: 'label',
				html: '<center><b>Feel the Goodness</b></center>'
			},
			{
				xtype: 'image',
				height: 480,
				src: ''
			},
			{
				xtype: 'label',
				html: 'Remember this?'
			},
			{
				xtype: 'sliderfield',
				label: 'How much did this shift your mood?',
				labelWidth: '40%',
				labelWrap: true,
				name: 'rate'
			},
			{
				xtype: 'button',
				action: 'rate',
				ui: 'confirm',
				text: 'Done'
			}
		]
	}

});