/*
 * File: app/view/emiFGM.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.emiFGM', {
	extend: 'Ext.form.Panel',
	xtype: 'feelgood',
	
	requires: [
		'Ext.ux.Fileup'
	],

	config: {
		showAnimation: 'slideIn',
		modal: false,
		items: [
			{
				xtype: 'label',
				html: '<center><b>Feel-Good Moment (FGM)</b></center>'
			},
			{
				xtype: 'label',
				html: 'Take a photo of something beautiful happening around you right now.'
			},
			{
				itemId: 'loadBtn',
				xtype: 'fileupload',
				autoUpload: false,
				loadAsDataUrl: true,
				url: '',
				states: {
					browse: {
						text: 'Press here to take photo...'
					},
					ready: {
						text: 'Upload'
					},
					uploading: {
						text: 'Loading'
					}
				},
			},
			{
				xtype: 'button',
				action: 'goback',
				ui: 'confirm',
				text: 'Done'
			}
		]
	}

});