/*
 * File: app/view/EMIGeneralMindfulness.js
 * Date: Wed Jul 17 2013 19:42:14 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMIGeneralMindfulness', {
	extend: 'Ext.form.Panel',

	config: {
		cls: 'breathLife',
		disabled: false,
		items: [
			{
				xtype: 'fieldset',
				goola: 'emi',
				centered: false,
				title: '<div align=\'center\'>Breathing With Life</div>',
				items: [
					{
						xtype: 'label',
						html: 'Wherever you are in this moment',
						itemId: 'describe',
						margin: '8px'
					},
					{
						xtype: 'checkboxfield',
						label: 'Feeling your feet planted on the ground',
						labelWidth: '80%',
						labelWrap: true
					},
					{
						xtype: 'checkboxfield',
						label: 'Feeling your breath supporting you',
						labelWidth: '80%',
						labelWrap: true,
						value: ''
					},
					{
						xtype: 'checkboxfield',
						label: 'Feeling your body just as it is',
						labelWidth: '80%',
						labelWrap: true
					},
					{
						xtype: 'checkboxfield',
						label: 'Breathing with everything',
						labelWidth: '80%',
						labelWrap: true
					},
					{
						xtype: 'checkboxfield',
						label: 'Just as it is',
						labelWidth: '80%',
						labelWrap: true
					},
					{
						xtype: 'button',
						action: 'exercise',
						text: 'Done'
					}
				]
			}
		]
	}

});