/*
 * File: app/view/EMIIntentionSet.js
 * Date: Mon Jul 01 2013 19:05:31 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMIIntentionSet', {
	extend: 'Ext.form.Panel',

	config: {
		hideAnimation: {
			type: 'fadeOut',
			duration: 768
		},
		showAnimation: {
			type: 'fadeIn',
			duration: 768
		},
		items: [
			{
				xtype: 'fieldset',
				itemId: 'fset',
				items: [
					{
						xtype: 'textareafield',
						itemId: 'intention',
						label: 'What would you like your intention to be for this week?',
						labelAlign: 'top',
						labelWrap: true,
						name: 'intention',
						maxLength: 100,
						placeHolder: 'Visualize the week ahead. Think about how do you want to live this week.'
					},
					{
						xtype: 'label',
						html: 'Example Intentions: <br/> <p>self-compassion<br/>patience<br/>acceptiance<br/>self-care</p>',
						itemId: 'example',
						style: 'color: rgb(128,128,128); font-size: 15px;'
					},
					{
						xtype: 'button',
						cls: 'button',
						disabled: true,
						itemId: 'done',
						text: 'Done'
					},
					{
						xtype: 'button',
						itemId: 'notnow',
						text: 'Not Now'
					}
				]
			}
		],
		listeners: [
			{
				fn: 'onTextareaChange',
				event: 'keyup',
				delegate: '#intention'
			},
			{
				fn: 'onIntentionSave',
				event: 'tap',
				delegate: '#done'
			},
			{
				fn: 'onNotNowTap',
				event: 'tap',
				delegate: '#notnow'
			}
		]
	},

	onTextareaChange: function(textfield, e, eOpts) {
		value = textfield.getValue().toUpperCase();
		button = textfield.parent.child('button');

		if(value.length<2){
			button.disable();
		}else{
			button.enable();
		}

		textfield.setValue(value);
	},

	onIntentionSave: function(button, e, eOpts) {
		text = button.parent.child('#intention').getValue();
		HEART.setItem('local', 'intention', text);

		content = this.getValues();

		content.type = this.emxType;

		HEART.toSensor(content);

		intentions = Ext.getStore("Intentions");

		store = {};
		store.text = text;
		store.timestamp = Date.now();
		intentions.add(store);
		intentions.sort("timestamp", 'DESC');		
		intentions.sync();

		//elements = Ext.ComponentQuery.query('#homePanel #editIntention');

		user = HEART.getItem('local', 'user');

		user = JSON.parse(user);
		user.intention = text;

		succ = function(response) {
			console.log(response);
		};

		fail = function(response) {
			console.log(response);
		};

		HEART.toUser( user, succ, fail );

		user = JSON.stringify(user);

		HEART.setItem('local', 'user', user);

		if(this.goola=='settings'){
			this.parent.pop();
		}else{
			button.parent.parent.destroy();
		}

	},

	onNotNowTap: function(button, e, eOpts) {
		if(this.goola=='settings'){
			this.parent.pop();
		}else{
			button.parent.parent.destroy();
		}

	}

});