/*
 * File: app/view/EMIMindHabitSet.js
 * Date: Fri Jun 28 2013 18:48:50 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMIMindHabitSet', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'fieldset',
				id: 'fset',
				title: 'Experiment with mindfulness...',
				items: [
					{
						xtype: 'label',
						html: 'Choose 1 activity for this week.<br/> See what it feels like to bring your full awareness to this. You can change it at any time.',
						itemId: 'describe',
						styleHtmlContent: true
					},
					{
						xtype: 'textfield',
						label: 'My mindful habit this week is:',
						labelAlign: 'top',
						labelWrap: true,
						name: 'mindful'
					},
					{
						xtype: 'selectfield',
						itemId: 'time',
						label: 'Remind me of this at',
						labelWidth: '65%',
						name: 'time'
					},
					{
						xtype: 'label',
						html: 'Example: <br/> Bring awareness to the sounds all around you right now. <br/> Be present when you hug or kiss anyone today. <br/>  Brush your teeth with awareness.',
						itemId: 'example',
						style: 'color: rgb(128,128,128); font-size: 13px',
						styleHtmlContent: true
					},
					{
						xtype: 'button',
						text: 'Done'
					}
				]
			}
		],
		listeners: [
			{
				fn: 'onFormpanelInitialize',
				event: 'initialize'
			}
		]
	},

	onFormpanelInitialize: function(component, eOpts) {
		time = this.child('#fset').child('#time');

		options = [];

		for( i=0; i<24; i++ ){	
			option = { text: i +': 00', value: i };	
			options.push(option);
			option = { text: i +': 30', value: i+0.5 };
			options.push(option);
		}


		time.setOptions(options);

	}

});