/*
 * File: app/view/emiMountain.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.emiMountain', {
	extend: 'Ext.form.Panel',

	config: {
		id: 'emiMountain',
		items: [
			{
				xtype: 'label',
				html: '<center><b>You are a Mountain</b></center>'
			},
			{
				xtype: 'label',
				html: 'Take your headphones & 10min to do this exercise from the workshop.<br><br>Press play when you are ready.'
			},
			{
				xtype: 'radiofield'
			},
			{
				xtype: 'button',
				itemId: 'mybutton5',
				text: 'Done!'
			}
		]
	}

});