/*
 * File: app/view/EMIMoments.js
 * Date: Wed Jul 17 2013 20:06:28 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMIMoments', {
	extend: 'Ext.form.Panel',

	config: {
		cls: 'moments',
		layout: {
			type: 'vbox'
		},
		items: [
			{
				xtype: 'label',
				html: '<br/><br/><br/>',
				itemId: 'empty'
			},
			{
				xtype: 'container',
				flex: 3,
				itemId: 'content',
				items: [
					{
						xtype: 'label',
						html: '￼What sensation is most present in your body now. Can you breath with it?',
						itemId: 'habit',
						listeners: [
							{
								fn: function(component, eOpts) {

								},
								event: 'initialize'
							}
						]
					}
				]
			},
			{
				xtype: 'container',
				flex: 1,
				itemId: 'handler',
				items: [
					{
						xtype: 'button',
						itemId: 'done',
						text: 'Done'
					}
				]
			}
		],
		listeners: [
			{
				fn: 'onOKTap',
				event: 'tap',
				delegate: '#done'
			}
		]
	},

	onOKTap: function(button, e, eOpts) {
		this.parent.pop();
	}

});