/*
 * File: app/view/EMIMindHabitSet.js
 * Date: Wed Jul 03 2013 19:25:12 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMIMindHabitSet', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'fieldset',
				id: 'fset',
				title: 'Experiment with mindfulness...',
				items: [
					{
						xtype: 'label',
						html: 'Choose 1 activity for this week.<br/> See what it feels like to bring your full awareness to this. You can change it at any time.',
						itemId: 'describe',
						styleHtmlContent: true
					},
					{
						xtype: 'textfield',
						itemId: 'mindful',
						label: 'My mindful habit this week is:',
						labelAlign: 'top',
						labelWrap: true,
						name: 'mindful'
					},
					{
						xtype: 'selectfield',
						itemId: 'time',
						label: 'Remind me of this at',
						labelWidth: '65%',
						name: 'time'
					},
					{
						xtype: 'label',
						html: 'Example: <p>Bring awareness to the sounds all around you right now. <br/> Be present when you hug or kiss anyone today. <br/> Brush your teeth with awareness.</p>',
						itemId: 'example',
						style: 'color: rgb(128,128,128); font-size: 13px'
					},
					{
						xtype: 'button',
						disabled: true,
						itemId: 'done',
						text: 'Done'
					}
				]
			}
		],
		listeners: [
			{
				fn: 'onTextfieldChange',
				event: 'keyup',
				delegate: '#mindful'
			},
			{
				fn: 'onHabitDoneTap',
				event: 'tap',
				delegate: '#done'
			},
			{
				fn: 'onFormpanelInitialize',
				event: 'initialize'
			}
		]
	},

	onTextfieldChange: function(textfield, e, eOpts) {
		value = textfield.getValue();
		button = textfield.parent.child('button');

		if(value.length<2){
			button.disable();
		}else{
			button.enable();
		}
	},

	onHabitDoneTap: function(button, e, eOpts) {
		text = button.parent.child('#mindful').getValue();

		user = HEART.getItem('local', 'user');

		user = JSON.parse(user);
		user.habit = text;

		user = JSON.stringify(user);

		HEART.setItem('local', 'user', user);

		this.parent.pop();
	},

	onFormpanelInitialize: function(component, eOpts) {
		time = this.child('#fset').child('#time');

		options = [];

		for( i=0; i<24; i++ ){	
			option = { text: i +': 00', value: i };	
			options.push(option);
			option = { text: i +': 30', value: i+0.5 };
			options.push(option);
		}

		time.setOptions(options);

	}

});