/*
 * File: app/view/EMITrackExercise.js
 * Date: Wed Jun 26 2013 11:06:36 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMITrackExercise', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'fieldset',
				height: 186,
				itemId: 'fieldSetExercise',
				title: 'Did you exercise today?',
				items: [
					{
						xtype: 'button',
						action: 'exercise',
						itemId: 'not',
						ui: 'decline',
						text: 'Not today'
					},
					{
						xtype: 'button',
						itemId: 'yes',
						ui: 'action',
						text: 'Yes'
					}
				]
			},
			{
				xtype: 'fieldset',
				hidden: true,
				itemId: 'fieldSetMinutes',
				title: 'How many minutes<br/>did you exercise?',
				items: [
					{
						xtype: 'numberfield',
						itemId: 'plus',
						label: 'min',
						labelAlign: 'right',
						name: 'time',
						required: true,
						minValue: 0
					},
					{
						xtype: 'button',
						action: 'exercise',
						itemId: 'done',
						text: 'Done'
					}
				]
			},
			{
				xtype: 'label',
				itemId: 'lblMins'
			}
		],
		listeners: [
			{
				fn: 'onNotTap',
				event: 'tap',
				delegate: '#not'
			},
			{
				fn: 'onYesTap',
				event: 'tap',
				delegate: '#yes'
			},
			{
				fn: 'onMyTimeSave',
				event: 'tap',
				delegate: '#done'
			}
		]
	},

	onNotTap: function(button, e, eOpts) {

	},

	onYesTap: function(button, e, eOpts) {

		var exercise = button.parent;
		var minutes = button.parent.parent.child('#fieldSetMinutes');
		minutes.child("#plus").setValue('');
		minutes.setShowAnimation({type: "fadeIn", duration: 1024});
		minutes.show();
		exercise.hide();
	},

	onMyTimeSave: function(button, e, eOpts) {
		exercise = HEART.getItem('local', 'exercise');
		plus = button.parent.child('textfield').getValue();

		if(exercise===null||isNaN(exercise)){
			exercise=0;
		}

		exercise = parseInt(exercise);
		plus = parseInt(plus);
		exercise += plus;

		HEART.setItem('local', 'exercise', exercise);
	},

	initialize: function() {
		exercise = HEART.getItem('local', 'exercise');

		if(exercise===null || isNaN(exercise)){
			exercise = 0;
		}
		var lbl = this.child("#lblMins");
		lbl.setHtml( "<div align='center'>"+ exercise +"min of exercise so far.</div>");

		var plus = this.child("#fieldSetMinutes").child("#plus");
		plus.setValue(0);
		this.callParent();
	}

});