/*
 * File: app/view/EMITrackMeditation.js
 * Date: Thu Apr 18 2013 15:14:35 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMITrackMeditation', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'fieldset',
				title: '<center>Did you meditate today?<center>',
				items: [
					{
						xtype: 'button',
						itemId: 'not',
						text: 'Not today'
					},
					{
						xtype: 'label',
						html: 'Yes. <br/><br/> How many minutes?',
						itemId: 'describe'
					},
					{
						xtype: 'textfield',
						itemId: 'mytextfield4',
						label: 'min',
						labelAlign: 'right',
						name: 'time',
						required: true
					},
					{
						xtype: 'button',
						itemId: 'mybutton36',
						text: 'Done'
					}
				]
			}
		],
		listeners: [
			{
				fn: 'onNotTap',
				event: 'tap',
				delegate: '#not'
			},
			{
				fn: 'onMyTimeChange',
				event: 'keyup',
				delegate: '#mytextfield4'
			},
			{
				fn: 'onMyTimeSave',
				event: 'tap',
				delegate: '#mybutton36'
			}
		]
	},

	onNotTap: function(button, e, eOpts) {
		var meditation = window.localStorage.getItem('meditation');

		if(meditation==null){
			meditation = 0;
		}

		Ext.Msg.alert(':)', "<div align='center'>["+ meditation +"]min meditated so far.</div>", Ext.emptyFn);
	},

	onMyTimeChange: function(textfield, e, eOpts) {
		var value = textfield.getValue();

		if(/\D+/.test(value)){
			Ext.Msg.alert(';(', "<div align='center'>Please don't enter letters or other characters.</div>", Ext.emptyFn);
			textfield.setValue(0);
		}
	},

	onMyTimeSave: function(button, e, eOpts) {
		var meditation = window.localStorage.getItem('meditation');
		var plus = button.parent.child('textfield').getValue();

		if(meditation==null){
			meditation=0;
		}

		meditation = parseInt(meditation);
		plus = parseInt(plus);

		meditation += plus;

		window.localStorage.setItem('meditation', meditation);

		var type = 'meditationTrack';
		var uuid = uuid;

		var content = { type: type, data: plus, user: uuid};

		var succ = function(response) {
			console.log(response);
		};

		var fail = function(response) {
			var feeds = Ext.getStore("Feeds");
			feeds.add({timestamp: Date.now(), type: type, data: plus, user: uuid});
			feeds.sort("timestamp", 'DESC');		
			feeds.sync();
		};

		AJAX.toSensor(content, succ, fail);

		if(this.goola=='exercises'){
			this.parent.pop();
		}else if(this.goola=='stressed'){
			this.parent.pop();
			this.parent.hide();
			this.parent.show();
		}else{
			this.destroy();
		}
	}

});