/*
 * File: app/view/EMITrackExercise.js
 * Date: Mon Apr 15 2013 18:51:05 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.EMITrackExercise', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'fieldset',
				title: '<center>Did you exercise today?<center>',
				items: [
					{
						xtype: 'button',
						text: 'Not today'
					},
					{
						xtype: 'label',
						html: 'Yes. <br/><br/> How many minutes?',
						itemId: 'describe'
					},
					{
						xtype: 'textfield',
						label: 'min',
						labelAlign: 'right',
						name: 'time'
					},
					{
						xtype: 'button',
						text: 'Done'
					}
				]
			}
		]
	}

});