/*
 * File: app/view/Experience.js
 * Date: Fri Jun 28 2013 13:01:40 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.Experience', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'fieldset',
				title: 'My Experience',
				items: [
					{
						xtype: 'label',
						html: 'Write a few words to capture your experiences today (emotions felt, your reactions, etc)',
						itemId: 'describe',
						styleHtmlContent: true,
						listeners: [
							{
								fn: function(component, eOpts) {
									component.element.on({
										tap : function(e, t){

											content = '<p>Do you have a moment to reflect on your day? “If you’d like, write a few words to capture your most salient experience and predominant emotions felt, and your relationship to this experience whether you observed it, reacted to it. Click for more background on this”</p>';

											Ext.create('Ext.Panel', {
												hideOnMaskTap: true,
												autoDestroy: true, 
												modal: true,
												html: content,
												padding: 10,
												left: 0
											}).showBy(component);

										}
									});
								},
								event: 'initialize'
							}
						]
					},
					{
						xtype: 'textfield',
						itemId: 'pleasant',
						label: 'Moments of pleasant feeling today? How did you respond?',
						labelAlign: 'top',
						labelWidth: '100%',
						labelWrap: true,
						name: 'pleasant'
					},
					{
						xtype: 'textfield',
						itemId: 'unpleasant',
						label: 'Moments of unpleasant feeling today? How did you respond?',
						labelAlign: 'top',
						labelWidth: '100%',
						labelWrap: true,
						name: 'unpleasant'
					},
					{
						xtype: 'image',
						height: 200,
						html: 'THANK YOU',
						itemId: 'heart',
						styleHtmlContent: true,
						src: 'heart_icon.png'
					},
					{
						xtype: 'button',
						itemId: 'done',
						text: 'Done'
					}
				]
			}
		]
	}

});