/*
 * File: app/view/IntentionSavorShare.js
 * Date: Tue Apr 16 2013 18:56:59 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.IntentionSavorShare', {
	extend: 'Ext.form.Panel',

	config: {
		items: [
			{
				xtype: 'fieldset',
				title: '<center>Feel Your Intention</center>',
				items: [
					{
						xtype: 'label',
						html: '<p>Your current intention is: <br/> <b>here.</b></p> <br/> <p>Take a few moments and savor the feelings and sensations of your intention.</p> <p>Take a moment to imagine sharing this with someone special.</p>'
					},
					{
						xtype: 'sliderfield',
						label: 'Can you feel it?<br/>(left=not at all, right=very much so)',
						labelAlign: 'top',
						labelWrap: true,
						value: [
							50
						]
					},
					{
						xtype: 'button',
						text: 'Done'
					},
					{
						xtype: 'button',
						text: 'Change my intention'
					}
				]
			}
		]
	}

});