/*
 * File: app/view/MainTabs.js
 * Date: Fri Jun 28 2013 19:35:26 GMT+0800 (CST)
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HEART.view.MainTabs', {
	extend: 'Ext.tab.Panel',
	alias: 'widget.mainview',

	config: {
		id: 'mainTabs',
		ui: 'light',
		hideAnimation: {
			type: 'fadeOut',
			duration: 256
		},
		showAnimation: {
			type: 'fadeIn',
			duration: 1024
		},
		layout: {
			animation: 'slide',
			type: 'card'
		},
		items: [
			{
				xtype: 'formpanel',
				title: 'Home',
				iconCls: 'home',
				id: 'homePanel',
				items: [
					{
						xtype: 'image',
						centered: false,
						docked: 'top',
						html: '<center><img src="heart_icon.png" height=111></center>',
						margin: '5px',
						maxWidth: '',
						style: '',
						ui: 'light',
						src: ''
					},
					{
						xtype: 'container',
						itemId: 'header',
						layout: {
							align: 'center',
							pack: 'center',
							type: 'hbox'
						},
						items: [
							{
								xtype: 'label',
								html: '<b>Welcome</b>',
								itemId: 'welcome',
								listeners: [
									{
										fn: function(component, eOpts) {
											component.element.on({
												tap : function(e, t){


													content='<p>“HEART stands for health enhancement, emotions, and resiliency training.” In addition to the workshops, we developed the HEART app to help you bring mindfulness into your day.</p>';

													content+='<p>HEART helps you to develop your own present moment awareness, to find greater calm and stability in the midst of your life’s changing conditions. The HEART app is here to help you work with various aspects of mindfulness—increasing awareness of your own body and mind states, and developing the capacity to “be with” whatever is happening in a more relaxed and balanced way.</p>';

													content+='<p>You can decide how you want to use the HEART app – using it in whatever way you find most supportive. More use of HEART should lead to greater stress resiliency.”</p>';

													Ext.create('Ext.Panel', {
														hideOnMaskTap: true,
														autoDestroy: true, 
														modal: true,
														html: content,
														padding: 10,
														left: 0
													}).showBy(component);

												}
											});
										},
										event: 'initialize'
									}
								]
							},
							{
								xtype: 'label',
								html: '<b>, [NAME] to H.E.A.R.T.</b>',
								itemId: 'sometext'
							}
						]
					},
					{
						xtype: 'label',
						html: '<center>My Meditation</center>',
						itemId: 'meditation',
						listeners: [
							{
								fn: function(component, eOpts) {
									component.element.on({
										tap : function(e, t){

										}
									});
								},
								event: 'initialize'
							}
						]
					},
					{
						xtype: 'container',
						itemId: 'myintention',
						layout: {
							align: 'center',
							pack: 'center',
							type: 'hbox'
						},
						items: [
							{
								xtype: 'selectfield',
								centered: false,
								itemId: 'intention',
								label: 'Intention',
								labelWidth: '50%',
								options: [
									{
										text: 'gggg',
										value: 'gggg'
									},
									{
										text: 'hhhh',
										value: 'hhhh'
									},
									{
										text: 'jjjj',
										value: 'jjjj'
									},
									{
										text: 'kkkk',
										value: 'kkkk'
									},
									
								]
							}
						]
					}
				]
			},
			{
				xtype: 'navigationview',
				title: 'I\'m stressed!',
				iconCls: 'user',
				id: 'stressed'
			},
			{
				xtype: 'navigationview',
				title: 'Exercises',
				iconCls: 'organize',
				id: 'exercises',
				items: [
					{
						xtype: 'list',
						id: 'exerciseList',
						hideOnMaskTap: true,
						allowDeselect: true,
						disableSelection: false,
						emptyText: 'Nothing',
						itemTpl: [
							'<div>{title}</div>'
						],
						pressedDelay: 64,
						store: 'EMXs',
						grouped: true
					}
				]
			},
			{
				xtype: 'navigationview',
				title: 'Settings',
				badgeText: '',
				iconCls: 'settings',
				hidden: false,
				itemId: 'settingsNav',
				items: [
					{
						xtype: 'formpanel',
						title: 'Settings',
						id: 'settings',
						autoDestroy: false,
						items: [
							{
								xtype: 'textfield',
								itemId: 'name',
								label: 'First name',
								labelWidth: '55%',
								labelWrap: true,
								name: 'name',
								autoCapitalize: true,
								maxLength: 15
							},
							{
								xtype: 'textfield',
								itemId: 'pid',
								label: 'Participant Id',
								labelWidth: '55%',
								labelWrap: true,
								name: 'pid'
							},
							{
								xtype: 'label',
								html: '<p>Please keep the app silent between:</p>',
								itemId: 'silent',
								style: 'color: rgb(128,128,128)'
							},
							{
								xtype: 'selectfield',
								itemId: 'awake',
								label: 'Awake Time',
								labelWidth: '55%',
								labelWrap: true,
								name: 'awake',
								readOnly: false
							},
							{
								xtype: 'selectfield',
								itemId: 'sleep',
								label: 'Sleep Time',
								labelWidth: '55%',
								labelWrap: true,
								name: 'sleep',
								readOnly: false
							},
							{
								xtype: 'label',
								html: '<p>Please remind me to fill out my Daily Log in the evening at:</p>',
								itemId: 'remind',
								style: 'color: rgb(128,128,128)'
							},
							{
								xtype: 'selectfield',
								itemId: 'daily',
								label: 'Daily Log Time',
								labelWidth: '55%',
								labelWrap: true,
								name: 'daily'
							},
							{
								xtype: 'button',
								itemId: 'saveSettings',
								text: 'Save'
							},
							{
								xtype: 'container',
								itemId: 'buttons',
								items: [
									{
										xtype: 'button',
										itemId: 'intention',
										text: 'Intention Set'
									},
									{
										xtype: 'button',
										itemId: 'mindful',
										text: 'Mindful Habit'
									},
									{
										xtype: 'button',
										itemId: 'notification',
										text: 'Notification Frequency'
									}
								]
							}
						]
					}
				]
			}
		],
		tabBar: {
			docked: 'bottom',
			ui: 'light',
			layout: {
				align: 'center',
				type: 'hbox'
			}
		},
		listeners: [
			{
				fn: 'onSaveSettingsTap',
				event: 'tap',
				delegate: '#saveSettings'
			},
			{
				fn: 'onIntentionSetTap',
				event: 'tap',
				delegate: '#intention'
			},
			{
				fn: 'onMindfullTap',
				event: 'tap',
				delegate: '#mindful'
			},
			{
				fn: 'onNotificationFrequencyTap',
				event: 'tap',
				delegate: '#notification'
			}
		]
	},

	onSaveSettingsTap: function(button, e, eOpts) {
		user = HEART.getItem('local', 'user');

		values = button.parent.getValues();

		var empty;

		for(field in values){
			if(values[field]=='')
			{ empty=true; break; }
		}

		if(empty){
			Ext.Msg.alert('Error', "You must fill out all information before continuing", Ext.emptyFn);
			return;
		}

		if(user!=null){
			user = JSON.parse(user);
			value = user.priority||2;	
			values.priority = value;
		}

		user = JSON.stringify(values);

		HEART.setItem('local', 'user', user);

		button.parent.child('#buttons').show();

		succ = function(response) {
			console.log(response);
		};

		fail = function(response) {
			console.log(response);
		};

		HEART.toUser( values, succ, fail );

		button.parent.parent.parent.setActiveItem(0);
		this.getTabBar().show();
	},

	onIntentionSetTap: function(button, e, eOpts) {
		form = Ext.create('HEART.view.EMIIntentionSet');
		form.emxType = 'EMIIntentionSet';
		form.goola = 'settings';
		button.parent.parent.parent.push(form);

	},

	onMindfullTap: function(button, e, eOpts) {
		form = Ext.create('HEART.view.EMIMindHabitSet');
		form.emxType = 'EMIMindHabitSet';
		form.goola = 'settings';
		button.parent.parent.parent.push(form);
	},

	onNotificationFrequencyTap: function(button, e, eOpts) {
		form = Ext.create('HEART.view.EMIPushSlider');
		form.emxType = 'EMIPushSlidert';
		form.goola = 'settings';
		button.parent.parent.parent.push(form);
	},

	initialize: function() {
		this.callParent();

		user = HEART.getItem('local','user');
		settingsNav = this.child('#settingsNav');
		settings = settingsNav.child('#settings');
		buttons = settings.child('#buttons');

		awakeOptions = [];

		for( i=5; i<12; i++ ){	
			option = { text: i +': 00', value: i };	
			awakeOptions.push(option);
			option = { text: i +': 30', value: i+0.5 };
			awakeOptions.push(option);
		}

		settings.child('#awake').setOptions(awakeOptions);

		sleepOptions = [];

		for( i=18; i<24; i++ ){	
			option = { text: i +': 00', value: i };	
			sleepOptions.push(option);
			option = { text: i +': 30', value: i+0.5 };
			sleepOptions.push(option);
		}

		settings.child('#sleep').setOptions(sleepOptions);

		dailyOptions = [];

		for( i=17; i<24; i++ ){
			option = { text: i+": 00", value: i };
			dailyOptions.push(option);
			option = { text: i+": 30", value: i+0.5 };
			dailyOptions.push(option);
		}

		settings.child('#daily').setOptions(dailyOptions);

		if( user===null ){
			this.setActiveItem(settingsNav);
			this.getTabBar().hide();
			buttons.hide();
		}else{
			user = JSON.parse(user);
			settings.setValues(user);
		}

		form = Ext.create('HEART.view.DAILYLOG');

		Ext.Viewport.add(form);
	}

});