/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({

});

Ext.application({

	requires: [
		'Ext.device.Device'
	],
	models: [
		'User',
		'Feed',
		'EMX'
	],
	stores: [
		'Feeds',
		'EMXs',
		'Users'
	],
	views: [
		'MainTabs',
		'EMIIntentionSet',
		'emaType1',
		'emaType2',
		'emaType3',
		'emiAudio1',
		'emiAudio2',
		'emiAudio3',
		'emiReflection1',
		'emiReflection2',
		'emiReflection3',
		'emiReflection4',
		'emiReflection5'
	],
	controllers: [
		'ExercisesController',
		'ExerciseController',
		'MainController'
	],
	name: 'HEART',

	launch: function() {

		Ext.create('HEART.view.MainTabs', {fullscreen: true});
	}

});
